const {
  ActionRowBuilder,
  ButtonBuilder,
  ButtonStyle,
  MessageFlags
} = require('discord.js');
const {
  ContainerBuilder,
  TextDisplayBuilder,
  SeparatorBuilder
} = require('@discordjs/builders');
const Guild = require('../../../models/guild/Guild');
const {
  createErrorEmbed,
  createSuccessEmbed
} = require('../../../utils/embeds/embedBuilder');
const { isGuildLeader } = require('../../../utils/guilds/guildMemberManager');
const { isGuildAdmin } = require('../../../utils/core/permissions');
const { sendDmOrFallback } = require('../../../utils/dm/dmFallback');
const { colors, emojis } = require('../../../config/botConfig');
const LoggerService = require('../../../services/LoggerService');

/**
 * Build invitation container for DM
 * @param {object} guildDoc - Guild document
 * @param {string} inviterUsername - Username of inviter
 * @returns {ContainerBuilder}
 */
function buildInviteContainer(guildDoc, inviterUsername) {
  const container = new ContainerBuilder();
  const primaryColor = typeof colors.primary === 'string'
    ? parseInt(colors.primary.replace('#', ''), 16)
    : colors.primary;
  container.setAccentColor(primaryColor);

  const titleText = new TextDisplayBuilder()
    .setContent(
      `# ${emojis.members || '👥'} Manager Invitation\n\n` +
      `You have been invited to be a **Manager** of the guild ` +
      `"${guildDoc.name}".\n\nAs a manager, you will be able to ` +
      `access and manage the guild panel.\n\nWould you like to accept?`
    );

  const detailsText = new TextDisplayBuilder()
    .setContent(
      `**Guild:** ${guildDoc.name}\n**Invited by:** ${inviterUsername}`
    );

  const footerText = new TextDisplayBuilder()
    .setContent(
      '*This invite was generated by the server bot. ' +
      'If you did not expect it, you can safely decline.*'
    );

  const timestampText = new TextDisplayBuilder()
    .setContent(`*<t:${Math.floor(Date.now() / 1000)}:R>*`);

  container.addTextDisplayComponents(titleText);
  container.addSeparatorComponents(new SeparatorBuilder());
  container.addTextDisplayComponents(detailsText);
  container.addTextDisplayComponents(footerText);
  container.addTextDisplayComponents(timestampText);

  return container;
}

/**
 * Handle manager invite confirmation
 * CustomId: manager:inviteConfirm:<guildId>:<userId>:yes|no
 * @param {import('discord.js').ButtonInteraction} interaction
 */
async function handle(interaction) {
  try {
    const parts = interaction.customId.split(':');
    const guildId = parts[2];
    const userId = parts[3];
    const decision = parts[4];

    if (!guildId || !userId || !decision) {
      const embed = createErrorEmbed('Invalid data', 'Missing confirmation.');
      return interaction.reply({
        components: [embed],
        flags: MessageFlags.IsComponentsV2 | MessageFlags.Ephemeral
      });
    }

    if (decision === 'no') {
      return interaction.update({ content: 'Action cancelled.', components: [] })
        .catch(() => {});
    }

    const guildDoc = await Guild.findById(guildId);
    if (!guildDoc) {
      const embed = createErrorEmbed('Guild not found', 'Guild not in DB.');
      return interaction.reply({
        components: [embed],
        flags: MessageFlags.IsComponentsV2 | MessageFlags.Ephemeral
      });
    }

    const member = await interaction.guild.members.fetch(interaction.user.id);
    const admin = await isGuildAdmin(member, interaction.guild.id);
    const isLeader = isGuildLeader(guildDoc, interaction.user.id);

    if (!admin && !isLeader) {
      const embed = createErrorEmbed('Permission denied', 'Not authorized.');
      return interaction.reply({
        components: [embed],
        flags: MessageFlags.IsComponentsV2 | MessageFlags.Ephemeral
      });
    }

    const managers = Array.isArray(guildDoc.managers) ? guildDoc.managers : [];

    if (managers.length >= 2) {
      const embed = createErrorEmbed('Limit reached', 'Max managers (2).');
      return interaction.update({ components: [embed] });
    }

    if (managers.includes(userId)) {
      const embed = createErrorEmbed('Already manager', 'User is manager.');
      return interaction.update({ components: [embed] });
    }

    const targetUser = await interaction.client.users.fetch(userId)
      .catch(() => null);
    if (!targetUser) {
      const embed = createErrorEmbed('Not found', 'User not found.');
      return interaction.update({ components: [embed] });
    }

    const container = buildInviteContainer(guildDoc, interaction.user.username);

    const accept = new ButtonBuilder()
      .setCustomId(`managerInvite:accept:${guildDoc._id}:${interaction.user.id}`)
      .setLabel('Accept')
      .setStyle(ButtonStyle.Success);

    const decline = new ButtonBuilder()
      .setCustomId(`managerInvite:decline:${guildDoc._id}`)
      .setLabel('Decline')
      .setStyle(ButtonStyle.Secondary);

    const row = new ActionRowBuilder().addComponents(accept, decline);

    const result = await sendDmOrFallback(
      interaction.client,
      guildDoc.discordGuildId,
      userId,
      { components: [container, row], flags: MessageFlags.IsComponentsV2 },
      {
        threadTitle: `Manager Invitation — ${guildDoc.name}`,
        reason: `Manager invite for user ${userId}`,
        mentionSupportRoles: true,
        includeSupportCloseButton: true
      }
    );

    if (!result.ok) {
      const embed = createErrorEmbed('Failed', 'Could not deliver invite.');
      return interaction.update({ components: [embed] });
    }

    const successEmbed = createSuccessEmbed(
      'Invitation sent',
      `Manager invitation sent to <@${userId}>.`
    );
    return interaction.update({ components: [successEmbed] });
  } catch (error) {
    LoggerService.error('Error in managerInviteConfirm:', { error });
    const embed = createErrorEmbed('Error', 'Could not send invitation.');
    if (interaction.deferred || interaction.replied) {
      return interaction.followUp({
        components: [embed],
        flags: MessageFlags.IsComponentsV2 | MessageFlags.Ephemeral
      });
    }
    return interaction.reply({
      components: [embed],
      flags: MessageFlags.IsComponentsV2 | MessageFlags.Ephemeral
    });
  }
}

module.exports = { handle };
