const {
  ActionRowBuilder,
  ButtonBuilder,
  ButtonStyle,
  MessageFlags
} = require('discord.js');
const {
  ContainerBuilder,
  TextDisplayBuilder,
  SeparatorBuilder
} = require('@discordjs/builders');
const Guild = require('../../models/guild/Guild');
const { isGuildLeader } = require('../../utils/guilds/guildMemberManager');
const { isGuildAdmin } = require('../../utils/core/permissions');
const {
  createErrorEmbed,
  createSuccessEmbed
} = require('../../utils/embeds/embedBuilder');
const { sendDmOrFallback } = require('../../utils/dm/dmFallback');
const { colors, emojis } = require('../../config/botConfig');

/**
 * User Select handler to invite a manager
 * CustomId: add_manager_user_select:<guildId>
 */
async function handle(interaction) {
  try {
    const [, guildId] = interaction.customId.split(':');
    const userId = interaction.values?.[0];
    if (!guildId || !userId) return interaction.deferUpdate();

    const guildDoc = await Guild.findById(guildId);
    if (!guildDoc) {
      const embed = createErrorEmbed('Not found', 'Guild not found.');
      return interaction.reply({
        components: [embed],
        flags: MessageFlags.IsComponentsV2 | MessageFlags.Ephemeral
      });
    }

    const member = await interaction.guild.members.fetch(interaction.user.id);
    const admin = await isGuildAdmin(member, interaction.guild.id);
    const isLeader = isGuildLeader(guildDoc, interaction.user.id);
    if (!admin && !isLeader) {
      const embed = createErrorEmbed(
        'Permission denied',
        'Only the guild leader can add managers.'
      );
      return interaction.reply({
        components: [embed],
        flags: MessageFlags.IsComponentsV2 | MessageFlags.Ephemeral
      });
    }

    const managers = Array.isArray(guildDoc.managers) ? guildDoc.managers : [];

    // Validate manager limit
    if (managers.length >= 2) {
      const embed = createErrorEmbed(
        'Limit reached',
        'The guild already has the maximum number of managers (2).'
      );
      return interaction.reply({
        components: [embed],
        flags: MessageFlags.IsComponentsV2 | MessageFlags.Ephemeral
      });
    }

    // Check if already a manager
    if (managers.includes(userId)) {
      const embed = createErrorEmbed(
        'Already a manager',
        'This user is already a manager of this guild.'
      );
      return interaction.reply({
        components: [embed],
        flags: MessageFlags.IsComponentsV2 | MessageFlags.Ephemeral
      });
    }

    // Fetch target user
    const targetUser = await interaction.client.users.fetch(userId)
      .catch(() => null);
    if (!targetUser) {
      const embed = createErrorEmbed('Not found', 'User not found.');
      return interaction.reply({
        components: [embed],
        flags: MessageFlags.IsComponentsV2 | MessageFlags.Ephemeral
      });
    }

    // Build DM invitation
    const container = new ContainerBuilder();
    const primaryColor = typeof colors.primary === 'string'
      ? parseInt(colors.primary.replace('#', ''), 16)
      : colors.primary;
    container.setAccentColor(primaryColor);

    const titleText = new TextDisplayBuilder()
      .setContent(
        `# ${emojis.members || '👥'} Manager Invitation\n\n` +
        `You have been invited to be a **Manager** of the guild ` +
        `"${guildDoc.name}".\n\nAs a manager, you will be able to ` +
        `access and manage the guild panel.\n\nWould you like to accept?`
      );

    const detailsText = new TextDisplayBuilder()
      .setContent(
        `**Guild:** ${guildDoc.name}\n` +
        `**Invited by:** ${interaction.user.username}`
      );

    const footerText = new TextDisplayBuilder()
      .setContent(
        '*This invite was generated by the server bot. ' +
        'If you did not expect it, you can safely decline.*'
      );

    const timestampText = new TextDisplayBuilder()
      .setContent(`*<t:${Math.floor(Date.now() / 1000)}:R>*`);

    container.addTextDisplayComponents(titleText);
    container.addSeparatorComponents(new SeparatorBuilder());
    container.addTextDisplayComponents(detailsText);
    container.addTextDisplayComponents(footerText);
    container.addTextDisplayComponents(timestampText);

    const accept = new ButtonBuilder()
      .setCustomId(
        `managerInvite:accept:${guildDoc._id}:${interaction.user.id}`
      )
      .setLabel('Accept')
      .setStyle(ButtonStyle.Success);

    const decline = new ButtonBuilder()
      .setCustomId(`managerInvite:decline:${guildDoc._id}`)
      .setLabel('Decline')
      .setStyle(ButtonStyle.Secondary);

    const row = new ActionRowBuilder().addComponents(accept, decline);

    // Send DM or fallback to thread
    const result = await sendDmOrFallback(
      interaction.client,
      guildDoc.discordGuildId,
      userId,
      {
        components: [container, row],
        flags: MessageFlags.IsComponentsV2
      },
      {
        threadTitle: `Manager Invitation — ${guildDoc.name}`,
        reason: `Manager invite for user ${userId}`,
        mentionSupportRoles: true,
        includeSupportCloseButton: true
      }
    );

    if (!result.ok) {
      const embed = createErrorEmbed(
        'Could not send invitation',
        'The invitation could not be delivered to the user.'
      );
      return interaction.reply({
        components: [embed],
        flags: MessageFlags.IsComponentsV2 | MessageFlags.Ephemeral
      });
    }

    const successEmbed = createSuccessEmbed(
      'Invitation sent',
      `A manager invitation was sent to <@${userId}>. ` +
      'They must accept it to become a manager.'
    );
    return interaction.reply({
      components: [successEmbed],
      flags: MessageFlags.IsComponentsV2 | MessageFlags.Ephemeral
    });
  } catch (error) {
    const container = createErrorEmbed(
      'Error',
      'Could not send the manager invitation.'
    );
    if (interaction.deferred || interaction.replied) {
      return interaction.followUp({
        components: [container],
        flags: MessageFlags.IsComponentsV2 | MessageFlags.Ephemeral
      });
    }
    return interaction.reply({
      components: [container],
      flags: MessageFlags.IsComponentsV2 | MessageFlags.Ephemeral
    });
  }
}

module.exports = { handle };
