const {
  ActionRowBuilder,
  ButtonBuilder,
  ButtonStyle,
  MessageFlags
} = require('discord.js');
const {
  ContainerBuilder,
  TextDisplayBuilder,
  SeparatorBuilder
} = require('@discordjs/builders');
const { colors, emojis } = require('../../config/botConfig');
const { sendDmOrFallback } = require('../dm/dmFallback');
const { getUserGuildInfo } = require('./userGuildInfo');

/**
 * Build the change co-leader invite container for DM
 * @param {object} guildDoc - Guild document
 * @param {string} inviterUsername - Username of the inviter
 * @param {string} currentCoLeaderUsername - Username of current co-leader being replaced
 * @returns {ContainerBuilder}
 */
function buildChangeCoLeaderInviteContainer(guildDoc, inviterUsername, currentCoLeaderUsername) {
  const container = new ContainerBuilder();
  const primaryColor = typeof colors.primary === 'string'
    ? parseInt(colors.primary.replace('#', ''), 16)
    : colors.primary;
  container.setAccentColor(primaryColor);

  const titleText = new TextDisplayBuilder()
    .setContent(
      `# ${emojis.star || '⭐'} Co-Leader Replacement Invitation\n\n` +
            `You have been invited to become the **Co-Leader** of ` +
            `"${guildDoc.name}", replacing the current co-leader **${currentCoLeaderUsername}**.\n\n` +
            `As a co-leader, you will have access to manage rosters and help lead the guild.\n\n` +
            `Would you like to accept?`
    );

  const detailsText = new TextDisplayBuilder()
    .setContent(
      `**Guild:** ${guildDoc.name}\n**Invited by:** ${inviterUsername}`
    );

  const footerText = new TextDisplayBuilder()
    .setContent(
      '*This invite was generated by the server bot. ' +
            'If you did not expect it, you can safely decline.*'
    );

  const timestampText = new TextDisplayBuilder()
    .setContent(`*<t:${Math.floor(Date.now() / 1000)}:R>*`);

  container.addTextDisplayComponents(titleText);
  container.addSeparatorComponents(new SeparatorBuilder());
  container.addTextDisplayComponents(detailsText);
  container.addTextDisplayComponents(footerText);
  container.addTextDisplayComponents(timestampText);

  return container;
}

/**
 * Send a DM co-leader replacement invitation to a user
 * @param {import('discord.js').Client} client
 * @param {string} targetUserId - Discord user ID to invite
 * @param {object} guildDoc - Guild document (Mongo)
 * @param {{ id: string, username?: string }} inviter - The inviter
 * @param {string} currentCoLeaderId - ID of co-leader to replace
 * @returns {Promise<{ok:boolean, error?:string}>}
 */
async function sendChangeCoLeaderInvite(client, targetUserId, guildDoc, inviter, currentCoLeaderId) {
  try {
    // Validate user is not in another guild
    if (guildDoc?.discordGuildId) {
      const { guild: existingGuild } = await getUserGuildInfo(
        guildDoc.discordGuildId,
        targetUserId
      );
      if (existingGuild && String(existingGuild._id) !== String(guildDoc._id)) {
        return {
          ok: false,
          error: `User is already in guild "${existingGuild.name}".`
        };
      }
    }

    const user = await client.users.fetch(targetUserId).catch(() => null);
    if (!user) return { ok: false, error: 'Target user not found.' };

    let currentCoLeaderName = 'Unknown';
    try {
      const oldVal = await client.users.fetch(currentCoLeaderId);
      if (oldVal) currentCoLeaderName = oldVal.username;
    } catch (_) { }

    const container = buildChangeCoLeaderInviteContainer(
      guildDoc,
      inviter?.username || `<@${inviter?.id}>`,
      currentCoLeaderName
    );

    const accept = new ButtonBuilder()
      .setCustomId(
        `changeCoLeaderInvite:accept:${guildDoc._id}:${inviter?.id || 'unknown'}:${currentCoLeaderId}`
      )
      .setLabel('Accept Replacement')
      .setStyle(ButtonStyle.Success);

    const decline = new ButtonBuilder()
      .setCustomId(`changeCoLeaderInvite:decline:${guildDoc._id}`)
      .setLabel('Decline')
      .setStyle(ButtonStyle.Secondary);

    const row = new ActionRowBuilder().addComponents(accept, decline);

    const title = `Co-Leader Invitation — ${guildDoc.name}`;
    const result = await sendDmOrFallback(
      client,
      guildDoc?.discordGuildId,
      targetUserId,
      { components: [container, row], flags: MessageFlags.IsComponentsV2 },
      {
        threadTitle: title,
        reason: `Co-leader replacement invite for user ${targetUserId}`,
        mentionSupportRoles: true,
        includeSupportCloseButton: true
      }
    );

    if (!result.ok) {
      return { ok: false, error: 'Could not deliver the invitation.' };
    }

    return { ok: true };
  } catch (error) {
    return { ok: false, error: 'Internal error while sending the invite.' };
  }
}

module.exports = { sendChangeCoLeaderInvite };
