const {
  ActionRowBuilder,
  ButtonBuilder,
  ButtonStyle,
  MessageFlags
} = require('discord.js');
const {
  ContainerBuilder,
  TextDisplayBuilder,
  SeparatorBuilder
} = require('@discordjs/builders');
const { colors, emojis } = require('../../config/botConfig');
const {
  getGuildTransitionStatus,
  formatRemaining
} = require('../rate-limiting/guildTransitionCooldown');
const { sendDmOrFallback } = require('../dm/dmFallback');
const { getUserGuildInfo } = require('../guilds/userGuildInfo');
const { logGuildInvite } = require('../guilds/activityLogger');
const { getRegionRosters } = require('./rosterManager');

/**
 * Send a DM roster invitation to a user with Accept/Decline buttons.
 * @param {import('discord.js').Client} client - Discord client
 * @param {string} targetUserId - Discord user ID to invite
 * @param {object} guildDoc - Guild document (Mongo)
 * @param {'main'|'sub'} roster - Roster type
 * @param {{ id: string, username?: string }} inviter - User who invited
 * @param {string} region - Region for the roster
 * @returns {Promise<{ok:boolean, error?:string}>}
 */
async function sendRosterInvite(
  client,
  targetUserId,
  guildDoc,
  roster,
  inviter,
  region
) {
  try {
    // Check cross-guild membership
    if (guildDoc?.discordGuildId) {
      const { guild: existingGuild } = await getUserGuildInfo(
        guildDoc.discordGuildId,
        targetUserId
      );
      if (existingGuild && String(existingGuild._id) !== String(guildDoc._id)) {
        return {
          ok: false,
          error: `User is already in guild "${existingGuild.name}".`
        };
      }
    }

    // Check region-specific roster
    const { mainRoster, subRoster } = getRegionRosters(guildDoc, region);
    const list = roster === 'main' ? mainRoster : subRoster;

    if (list.includes(targetUserId)) {
      return { ok: false, error: `User is already in this roster for ${region}.` };
    }
    if (list.length >= 5) {
      return { ok: false, error: `Roster full for ${region} (limit: 5).` };
    }

    // Cooldown check
    if (guildDoc?.discordGuildId) {
      try {
        const { active, remainingMs, lastLeftGuildId } =
          await getGuildTransitionStatus(guildDoc.discordGuildId, targetUserId);
        if (active && String(guildDoc._id) !== String(lastLeftGuildId)) {
          const remaining = formatRemaining(remainingMs);
          return {
            ok: false,
            error: `User on cooldown. Wait ${remaining}.`
          };
        }
      } catch (_) { /* ignore */ }
    }

    const user = await client.users.fetch(targetUserId).catch(() => null);
    if (!user) return { ok: false, error: 'Target user not found.' };

    const rosterLabel = roster === 'main' ? 'Main Roster' : 'Sub Roster';

    const container = new ContainerBuilder();
    const primaryColor = typeof colors.primary === 'string'
      ? parseInt(colors.primary.replace('#', ''), 16)
      : colors.primary;
    container.setAccentColor(primaryColor);

    const titleText = new TextDisplayBuilder()
      .setContent(
        `# ${emojis.members || '👥'} Guild Roster Invitation\n\n` +
        `You have been invited to join the ${rosterLabel} of ` +
        `guild "${guildDoc?.name || 'Unknown'}" for region **${region}**.`
      );

    const detailsText = new TextDisplayBuilder()
      .setContent(
        `**Guild:** ${guildDoc?.name || 'Unknown'}\n` +
        `**Roster:** ${rosterLabel}\n` +
        `**Region:** ${region}\n` +
        `**Invited by:** ${inviter?.username || `<@${inviter?.id}>`}`
      );

    const footerText = new TextDisplayBuilder()
      .setContent('*This invite was generated by the bot.*');

    const timestampText = new TextDisplayBuilder()
      .setContent(`*<t:${Math.floor(Date.now() / 1000)}:R>*`);

    container.addTextDisplayComponents(titleText);
    container.addSeparatorComponents(new SeparatorBuilder());
    container.addTextDisplayComponents(detailsText);
    container.addTextDisplayComponents(footerText);
    container.addTextDisplayComponents(timestampText);

    // Encode region for safe customId (replace spaces with underscores)
    const safeRegion = region.replace(/ /g, '_');

    // Include region in button customIds
    const accept = new ButtonBuilder()
      .setCustomId(
        `rosterInvite:accept:${guildDoc._id}:${roster}:${inviter?.id || 'unknown'}:${safeRegion}`
      )
      .setLabel('Join Guild')
      .setStyle(ButtonStyle.Success);

    const decline = new ButtonBuilder()
      .setCustomId(`rosterInvite:decline:${guildDoc._id}:${roster}:${safeRegion}`)
      .setLabel("Don't Join")
      .setStyle(ButtonStyle.Secondary);

    const row = new ActionRowBuilder().addComponents(accept, decline);

    // Try DM first, fallback to private thread in dm-warning channel if DMs are disabled
    const title = `Roster Invitation — ${guildDoc?.name || 'Guild'}`;
    const result = await sendDmOrFallback(
      client,
      guildDoc?.discordGuildId,
      targetUserId,
      {
        components: [container, row],
        flags: MessageFlags.IsComponentsV2
      },
      {
        threadTitle: title,
        reason: `Roster invite fallback for user ${targetUserId}`,
        mentionSupportRoles: true,
        includeSupportCloseButton: true
      }
    );

    if (!result.ok) return { ok: false, error: 'Could not deliver the invitation.' };

    // Log guild invite activity
    try {
      const inviterUsername = inviter?.username || inviter?.tag || inviter?.id;
      const inviteeUsername = user?.username || user?.tag || targetUserId;
      await logGuildInvite(
        guildDoc.discordGuildId,
        String(guildDoc._id),
        guildDoc.name,
        inviter?.id,
        inviterUsername,
        targetUserId,
        inviteeUsername,
        roster
      );
    } catch (_) {}

    return { ok: true };
  } catch (error) {
    return { ok: false, error: 'Internal error while sending the invite.' };
  }
}

module.exports = { sendRosterInvite };


